
export const THREAD_CHAT_TYPES = {
  CHAT: "CHAT", 
  ROOM: "ROOM", 
  CAMPAIGN: "CAMPAIGN"
}

export const MESSAGE_TYPES: {[index: string]: string} = {
  BEFRIEND_REQUEST: 'BEFRIEND_REQUEST',
  BEFRIEND_ACCEPT: 'BEFRIEND_ACCEPT',
  BEFRIEND_REJECT: 'BEFRIEND_REJECT',
  CAMPAIGN_INVITE: 'CAMPAIGN_INVITE',
  CAMPAIGN_INVITE_ACCEPT: 'CAMPAIGN_INVITE_ACCEPT',
  CAMPAIGN_INVITE_REJECT: 'CAMPAIGN_INVITE_REJECT',
  END_FRIENDSHIP: 'END_FRIENDSHIP',
  EXIT_CAMPAIGN: 'EXIT_CAMPAIGN',
  PROMOTE_TO_DM: 'PROMOTE_TO_DM',
  REMOVE_FROM_CAMPAIGN: 'REMOVE_FROM_CAMPAIGN',
  ROOM_INVITE: "ROOM_INVITE",
  ROOM_INVITE_ACCEPT: "ROOM_INVITE_ACCEPT",
  ROOM_INVITE_REJECT: "ROOM_INVITE_REJECT",
  STEP_DOWN_DM: 'STEP_DOWN_DM',
  TEXT_ONLY: 'TEXT_ONLY',
}

export const MESSAGE_TYPE_ARR = Object.values(MESSAGE_TYPES);

export const RESPONSE_MESSAGE_TYPES: {[index: string]: string} = {
  BEFRIEND_ACCEPT: 'BEFRIEND_ACCEPT',
  BEFRIEND_REJECT: 'BEFRIEND_REJECT',
  CAMPAIGN_INVITE_ACCEPT: 'CAMPAIGN_INVITE_ACCEPT',
  CAMPAIGN_INVITE_REJECT: 'CAMPAIGN_INVITE_REJECT',
  ROOM_INVITE_ACCEPT: "ROOM_INVITE_ACCEPT",
  ROOM_INVITE_REJECT: "ROOM_INVITE_REJECT",
};

export const RESPONSE_MESSAGE_TYPE_ARR = Object.values(RESPONSE_MESSAGE_TYPES);

const { CHAT, ROOM, CAMPAIGN } = THREAD_CHAT_TYPES;
const THREAD_CHAT_TYPES_ARRAY: string[] = [CHAT, ROOM, CAMPAIGN] as const;


export type ChatTypes = typeof THREAD_CHAT_TYPES_ARRAY[number]